### ISSUE TITLE
Tracking issue for adding curve offsetting

### ISSUE THREAD

**Issue by ctrlcctrlv** [linebender/kurbo#132]
Am I missing something, or is it not implemented as yet?

**Comment by raphlinus** [comment]
It is not implemented yet. I am very interested in the subject and will probably do it, if for no other reason than to get stroking right (though see the recent [polar stroking](https://arxiv.org/abs/2007.00308) paper), but it is not there yet.

Happy to have this open as a tracking issue.

**Comment by ctrlcctrlv** [comment]
Cool :) I hope when you do it, there will be support for graduated curves, which are quite rare in these libraries. 
![2577](https://user-images.githubusercontent.com/838783/93003699-c35c6a80-f4f5-11ea-9f8f-fbf22a60efa1.jpg)

**Comment by ctrlcctrlv** [comment]
(The pictures in that paper are very beautiful, I wonder if @Skef has seen them.)

**Comment by raphlinus** [comment]
Yeah, it's very much on my radar and have had some discussions about that. But I'm likely to start with what's needed to implement stroke from the PostScript imaging model, which is of course uniform width.

The Spiro-to-Bezier conversion tools attached to my thesis have some offset capability, but it's not numerically robust. 

[Comparing Offset Curve Approximation Methods](https://pdfs.semanticscholar.org/9ac1/978746ec54bdd555b906e2ea1eb922cd6ffd.pdf) is one of the best academic papers on the topic, but there might be more recent work (in addition to the polar stroking cited above, and likely some of its references). If I had to do it today, I'd probably take the curve to quadratic beziers (that method already exists), solve it there, paying special attention to cusps, where having a reasonably simple closed-form formula for curvature helps, then if conversion back into cubics is desired, use techniques similar to my thesis. (There are also use cases where the end product can be quadratics or even flattened, of course)

Another fascinating source is the German paper [Die Parallelkurve der Klothoide](https://books.google.com/books?id=UvpZAAAAYAAJ&pg=PA373&lpg=PA373&dq=%22Die+Parallelkurve+der+Klothoide%22&source=bl&ots=fuY39VdPpd&sig=K0AbL03rXAm_g4J9KsheQbbxyaA&hl=en&sa=X&ved=2ahUKEwiUrcD1poTfAhVvFjQIHVthBPoQ6AEwAnoECAMQAQ#v=onepage&q=%22Die%20Parallelkurve%20der%20Klothoide%22&f=false), which gives a closed form analytic solution for Euler spirals (clothoids). I have in my queue a draft English translation (most of the translation work done by @Rahix) but haven't polished it enough to publish yet. I'd be happy to share it privately to those really interested. One reason this might be a good primitive is that it's trivially easy to identify where the cusps are because curvature is just a linear equation.

**Comment by skef** [comment]
@ctrlcctrlv The paper is quite recent but I recognize some of the images so I may have run into a preprint last year.

Most of its content isn't directly relevant to your own interests, though, as it concerns a strategy for tessellation rather than stroke-to-path. That's a distinction worth clarifying in this issue: Is it about rendering a font in a stroked format or working with source strokes to produce vectorized output? 

There's some interesting content about cusps but mostly relating to cusps on cubic source curves, which is a problem one could devote weeks to and help maybe 2 font developers ever. General rasterizers have to deal with this stuff but with font tools it's acceptable to barf and let the designer pick a different way to express their problem. Not only acceptable but preferable, if those hours are spent adding more functionality. 

(On a quick reading the tessellation algorithm likely also handles offset-generated cusps in a more PostScript-y way but apparently people don't care much about that. Skia currently just give the offsetting result and the general feeling seems to be "if you don't want that to happen don't make your splines that way":

![cusp](https://user-images.githubusercontent.com/6175836/93005003-a88ff300-f501-11ea-8437-5ddc9b60f68c.png)

However, it's possible the new GPU-based code being developed by @csmartdalton86 will change that.)

**Comment by derekdreery** [comment]
I'm experimenting with curve offsetting, and am having a problem with offsetting the following path:
```
MoveTo((-2170.095353, -369.635396))
CurveTo((-2115.655477, -218.488925), (-2086.476682, 37.495795), (-2017.549469, 213.217522))
CurveTo((-1988.684268, 286.80592), (-1931.866027, 403.702586), (-1811.798699, 447.97435))
CurveTo((-1704.288268, 487.616078), (-1606.264846, 439.274184), (-1569.373961, 419.464496))
CurveTo((-1449.942582, 355.33217), (-1329.376678, 226.071128), (-1222.780998, 151.761415))
CurveTo((-1171.510239, 116.019673), (-1151.066708, 113.2024), (-1151.066708, 113.2024))
CurveTo((-1151.120216, 113.209773), (-1152.110599, 113.337442), (-1153.897098, 113.285075))
CurveTo((-1155.705595, 113.232064), (-1156.693909, 113.044344), (-1156.74149, 113.034924))
CurveTo((-1156.682693, 113.046565), (-1135.106074, 117.341341), (-1082.25735, 159.659778))
CurveTo((-983.106035, 239.05486), (-880.606905, 362.283071), (-776.270861, 421.729668))
CurveTo((-752.242446, 435.420119), (-662.146044, 485.833772), (-560.15685, 447.715776))
CurveTo((-496.724316, 424.008156), (-423.874136, 368.363237), (-367.727038, 243.251493))
CurveTo((-304.447983, 102.247716), (-276.097721, -97.22858), (-295.482424, -275.120373))
```
I'll see if I can refine this down to the offending curve.

**Comment by ctrlcctrlv** [comment]
You should be able to test that quite easily. What if you add f64::EPSILON to both x and y, or even just one or the other?
