### ISSUE TITLE
Enable `RoundedRect` to change the radius on all four corners

### ISSUE THREAD

**Issue by N3xed** [linebender/kurbo#138]
Currently, to do this, you'd have to do the same thing as the `Shape` implementation for `RoundedRect` does, with the exception that each corner could have a different radius (or none). It would also make it much easier to implement styling of all corners in `druid`.

The overhead on `RoundedRect` would be minimal. This could easily be implemented by making `RoundedRectPathIter::arcs` `Option<T>`s and adding three more `f64` for each corner in `RoundedRect`. I'm not sure how a non-rounded corner (ie. zero radius) should be specified. Two possibilities are making the radius variables in `RoundedRect` also `Option` or when creating the `RoundedRectPathIter` comparing the radius to some minimum value.

I will implement this if I get the Ok and some feedback on the problem I mentioned.

**Comment by ZhennanWu** [comment]
Just dropping by. It seems that kurbo still lacks the elliptically rounded rectangles, which [flutter supports](https://api.flutter.dev/flutter/dart-ui/RRect-class.html). Basically we just need to use two parameters per corner (radius_X, radius_Y) to describe the rounding radius. Note that this cannot be emulated by an affine transform on existing `RoundedRect`, since the four corners may uses wildly different ellipses.

I haven't really encountered anything significant in Flutter that uses this feature. But this is concerning when trying to emulate Flutter.

Unfortunately, if this is implemented on current RoundedRect, it will be a breaking (?) change. Or we could add a second type (though the name could probably be mouthful). Or we could choose to not implement.
