### ISSUE TITLE
Affine * Rect ?

### ISSUE THREAD

**Issue by gumptious** [linebender/kurbo#168]
Hey there — I noticed in the code comments that a `TranslateScale` via `Mul`  is the recommended (only?) way to transform a `Rect` right now.  For my use-case I'd like to apply an arbitrary `Affine` transform to `Rect`s, e.g. including rotation.

Is `TranslateScale`-only for `Rect` an intentional design decision, has support simply not been implemented, or is something else afoot?  If it's a matter of "not-yet-implemented," could you give a brain-dump of constraints/TODOs to help a would-be contributor?

I dug through the code, docs, and GH issues but haven't found any clues yet.  Thanks in advance!  Impressed by both `kurbo` and `piet` from my tire-kicking.

**Comment by raphlinus** [comment]
It's intentional, as `Rect` is constrained to be axis-aligned, while `Affine` can do general rotations and shears. If we had a parallelogram shape, then we could do `Affine` * `Rect` -> `Parallelogram`, but there hasn't yet been a strong use case for it. Obviously it's possible to take any shape (including a rectangle) into a `BezPath`.

If it ends up that your use case strongly motivates a parallelogram shape, I'm happy to provide pointers on how to get that done. Implementing a `Shape` is fun, though requires rigorous mathematical and geometric reasoning. I'm in the middle of doing it for piecewise Euler spiral paths.

**Comment by gumptious** [comment]
Thanks for the quick response!

My use-case is more or less a 2D game engine: an "app engine" with an animation-intensive twist.  In this system, hierarchical affine transforms are managed by a scene graph.  

So for example I may have a `Rect` that's a descendant of two subsequent `Group`s in the scene graph, where each of those `Group`s supports arbitrary affine transforms including rotation and shear.  For a given frame, the transform I'd like to apply to the leaf-node `Rect` is the accumulated multiplication of the transform matrices of its ancestors.  In this world, even though it was a `Rect` that went in at author-time, it is some kind of parallelogram that gets rendered, due to the contortions of the `Group`s that contain it.

With this detail, does it seem to you like authoring a `Parallelogram` `Shape` is the right answer?  Stitching together `CurvyRect`s from beziers would also work for me, modulo performance concerns.  My gut feeling is that I want a `Rect` that's willing to explore new modes of axis-alignment.  Maybe that looks something like `Affine * Rect -> Parallelogram`, or perhaps `Affine * Rect -> Rect` where`Rect` knows how to draw its affine-transformed self (even if that happens to look like a parallelogram)

**Comment by derekdreery** [comment]
I would think `Affine * Rect -> BezPath` makes the most sense.

**Comment by raphlinus** [comment]
This *does* sound like a parallelogram to me, and I lean towards implementing that shape. The concept of `Shape` is deliberately an open-ended trait, rather than an enum, to support cases like this.

One of the interesting methods here is [as_rect()](https://docs.rs/kurbo/0.8.0/kurbo/trait.Shape.html#method.as_rect), which would let you get a `Rect` at the end assuming the transform is axis-aligned.

One suggestion for the representation: a parallelogram is the affine transformation of the unit square, so you could just store that. That would make operations such as applying an transform quite simple, and there are already helpful methods like `determinant` to give you the area and `transform_rect_bbox` to give you the bounding box.

**Comment by cmyr** [comment]
To answer the other question: `TranslateScale` was implemented explicitly for this purpose, and it does have a `Mul<Rect>` implementation.

**Comment by derekdreery** [comment]
> One suggestion for the representation: a parallelogram is the affine transformation of the unit square

Neat! Then you could use ellipse (which is an affine transformation of the unit circle) as inspiration.

**Comment by gumptious** [comment]
Thank you all for the details & thinking.

> a parallelogram is the affine transformation of the unit square, so you could just store that

> you could use ellipse (which is an affine transformation of the unit circle) as inspiration

I noticed that about ellipse and appreciated its design! That seems like a solid approach for `Parallelogram`; I agree and thank you for the pointer.

Here's my plan for now:  heed your original advice to represent my rectangles with `BezPath`.  If I hit any bottlenecks or walls, I'll revisit `Parallelogram`.  Cheers!
