### ISSUE TITLE
[`BezPath::get_seg`] should not produce segment for `ClosePath` element if current position is equal to previous `MoveTo`

### ISSUE THREAD

**Issue by ctrlcctrlv** [linebender/kurbo#214]
I already can't use it in glifparser due to #211, but this issue is yet another blocker.

https://github.com/linebender/kurbo/blob/b9247ed0a872cdd63a5b3c64ca5bc1e1392abee8/src/bezpath.rs#L322-L325

There is truly no line there on e.g. a circle. This is just attempting to work around the rather clumsy PostScript-ism of even having "move" points in non-move shapes (closed shapes).

**Comment by cmyr** [comment]
Can you elaborate? the following code, for me, produces 4 cubic segments:

```rust
let circ = Circle::new(Point::ZERO, 10.0);
let segments: Vec<_> = circ.path_segments(1.0).collect();
dbg!(segments);
```

output:

```
[src/main.rs:17] segments = [
    Cubic(
        CubicBez {
            p0: (10.0, 0.0),
            p1: (10.0, 5.51915024494),
            p2: (5.5191502449400005, 10.0),
            p3: (0.0000000000000006123233995736766, 10.0),
        },
    ),
    Cubic(
        CubicBez {
            p0: (0.0000000000000006123233995736766, 10.0),
            p1: (-5.519150244939999, 10.0),
            p2: (-9.999999999999998, 5.5191502449400005),
            p3: (-10.0, 0.0000000000000012246467991473533),
        },
    ),
    Cubic(
        CubicBez {
            p0: (-10.0, 0.0000000000000012246467991473533),
            p1: (-10.0, -5.519150244939999),
            p2: (-5.519150244940002, -9.999999999999998),
            p3: (-0.0000000000000018369701987210296, -10.0),
        },
    ),
    Cubic(
        CubicBez {
            p0: (-0.0000000000000018369701987210296, -10.0),
            p1: (5.519150244939998, -10.0),
            p2: (10.0, -5.51915024494),
            p3: (10.0, 0.0),
        },
    ),
]
```

**Comment by cmyr** [comment]
Also just a meta point: the "for no good reason" part of this issue title doesn't seem particularly useful, to me. If this is a bug, then by definition there is no 'good reason' for the behaviour, because the behaviour was not intended and so not rationalized. If it is *not* a bug, then there likely is a reason for the behaviour, and whether or not it is a 'good reason' is A) potentially subjective and B) *at the very least* cannot be determined without *knowledge of what the reason is*, which knowledge must be missing at the time the issue is opened.

You and I have an existing relationship, so I understand that you are not trying to be difficult, but if I were to see this issue title pop up in my notifications from somebody I did not know I would almost certainly just ignore it, assuming that whoever had opened it was not somebody I am interested in collaborating with.

Also while I'm here (😇):

This issue also does a very poor job of describing the problem that you're encountering, because I don't have any information about how to reproduce it. Pointing to a potential problem line in kurbo is an okay starting point, but it's also helpful to show how you got there.

Most of the other API for converting elements to segments does check for point equality in the `ClosePath` case, and avoids creating a `PathSeg` when it would be zero-length.

**Comment by cmyr** [comment]
I've updated the title, and I do think there is at the very least an inconsistency here: the behaviour of `get_seg` is different from the behaviour of the segments iterator, which correctly handles this case.

Another consideration: currently we use an equality test to decide if we add this final line, but it would probably be better to compare against some epsilon, possibly taking the provided `accuracy` parameter into account.

**Comment by raphlinus** [comment]
Agree that get_seg should be consistent with segments iterator. I also think equality is the correct test and basically make that assumption in piet_gpu as well. In the case of an epsilon match, you'll get an epsilon-length segment, which I think the consumer of the API can make a reasonable decision what to do with.
