### ISSUE TITLE
error[E0369]: cannot multiply `kurbo::Point` by `Affine`

### ISSUE THREAD

**Issue by ctrlcctrlv** [linebender/kurbo#217]
I think this should be reciprocal. Maybe? Just not understanding why I can `m*p` but not `p*m` but you may have a good reason.

**Comment by raphlinus** [comment]
It's just not the way matrices work.

**Comment by ctrlcctrlv** [comment]
Your matrix type or all matrices?

**Comment by raphlinus** [comment]
So basically it's traditional to represent an affine transformation as a matrix (A), and a vector as a column (x). There's the additional complication of the additional "1" added to represent the translation component, but ignore that, it's not relevant. Then Ax has the right shape, but xA is a shape error. You can write x^T A, but (off the top of my head) it's not particularly meaningful. That's why it's only one way.

**Comment by ctrlcctrlv** [comment]
I see, thanks. These are typically reciprocal in libraries but I won't pretend to know more about math than Raph lol
