### ISSUE TITLE
Add EdgeInsets type

### ISSUE THREAD

**Issue by cmyr** [linebender/kurbo#63]
This would be a type that could be used to describe the distance between the edges of two rectangles.

```rust
struct EdgeInsets {
    top: f64,
    right: f64,
    bottom: f64,
    left: f64,
}
```

operators: `rect +- insets => rect`, and possibly `rect - rect => insets`.

from/into: `From<f64>` is uniform insets; `From<(f64, f64)>` is uniform top/bottom and left/right. `From<(f64, f64, f64, f64)>` is as expected.

**Comment by raphlinus** [comment]
Sounds good to me. Perhaps simply `Insets` is a better name, I don't see how "edge" adds much.

For the algebraic operations, we should be careful that they follow mathematical rules. That means mostly that size can go negative. I *think* a very good complement to this type would be a `nonnegative` method on `Rect` that converts negative sizes to zero (suggestions for a better name quite welcome).

**Comment by raphlinus** [comment]
Why trbl as the order? Rect is ltrb, which I personally think is more natural. Another point relevant for documentation is that "top" and "bottom" aren't good names in the kurbo universe because we ostensibly support both graphics-style (y-down) and math-style (y-up) coordinate systems. See [Rect docs](https://docs.rs/kurbo/0.5.1/kurbo/struct.Rect.html) for more details.

**Comment by cmyr** [comment]
I just followed the rules for CSS padding. As these are chiefly intended for UI layout, top and bottom are the most intuitive names, but I'm open to suggestions.
